import { mutation, query } from "./_generated/server";
import { components } from "./_generated/api";
import { defineCodexHostDefinitions } from "@zakstam/codex-local-component/host/convex";

export { getActorBindingForBootstrap, listThreadsForPicker, listRuntimeConversationBindingsForPicker, resolveOpenTarget } from "./chat.extensions";

const codex = defineCodexHostDefinitions({ components });

export const syncOpenConversationBinding = mutation(codex.mutations.syncOpenConversationBinding);
export const markConversationSyncProgress = mutation(codex.mutations.markConversationSyncProgress);
export const forceRebindConversationSync = mutation(codex.mutations.forceRebindConversationSync);
export const startConversationSyncSource = mutation(codex.mutations.startConversationSyncSource);
export const appendConversationSyncSourceChunk = mutation(codex.mutations.appendConversationSyncSourceChunk);
export const sealConversationSyncSource = mutation(codex.mutations.sealConversationSyncSource);
export const cancelConversationSyncJob = mutation(codex.mutations.cancelConversationSyncJob);
export const ensureConversationBinding = mutation(codex.mutations.ensureConversationBinding);
export const archiveConversation = mutation(codex.mutations.archiveConversation);
export const unarchiveConversation = mutation(codex.mutations.unarchiveConversation);
export const ensureSession = mutation(codex.mutations.ensureSession);
export const ingestEvent = mutation(codex.mutations.ingestEvent);
export const ingestBatch = mutation(codex.mutations.ingestBatch);
export const deleteThread = mutation(codex.mutations.deleteThread);
export const scheduleDeleteThread = mutation(codex.mutations.scheduleDeleteThread);
export const deleteTurn = mutation(codex.mutations.deleteTurn);
export const scheduleDeleteTurn = mutation(codex.mutations.scheduleDeleteTurn);
export const purgeActorData = mutation(codex.mutations.purgeActorData);
export const schedulePurgeActorData = mutation(codex.mutations.schedulePurgeActorData);
export const cancelDeletion = mutation(codex.mutations.cancelDeletion);
export const forceRunDeletion = mutation(codex.mutations.forceRunDeletion);
export const respondApproval = mutation(codex.mutations.respondApproval);
export const upsertTokenUsage = mutation(codex.mutations.upsertTokenUsage);
export const interruptTurn = mutation(codex.mutations.interruptTurn);
export const upsertPendingServerRequest = mutation(codex.mutations.upsertPendingServerRequest);
export const resolvePendingServerRequest = mutation(codex.mutations.resolvePendingServerRequest);
export const acceptTurnSend = mutation(codex.mutations.acceptTurnSend);
export const failAcceptedTurnSend = mutation(codex.mutations.failAcceptedTurnSend);

export const validateHostWiring = query(codex.queries.validateHostWiring);
export const getConversationSyncJob = query(codex.queries.getConversationSyncJob);
export const listConversationSyncJobs = query(codex.queries.listConversationSyncJobs);
export const listThreadsForConversation = query(codex.queries.listThreadsForConversation);
export const getDeletionStatus = query(codex.queries.getDeletionStatus);
export const persistenceStats = query(codex.queries.persistenceStats);
export const durableHistoryStats = query(codex.queries.durableHistoryStats);
export const dataHygiene = query(codex.queries.dataHygiene);
export const threadSnapshotByConversation = query(codex.queries.threadSnapshotByConversation);
export const listThreadMessagesByConversation = query(codex.queries.listThreadMessagesByConversation);
export const listTurnMessagesByConversation = query(codex.queries.listTurnMessagesByConversation);
export const listPendingApprovals = query(codex.queries.listPendingApprovals);
export const listTokenUsageByConversation = query(codex.queries.listTokenUsageByConversation);
export const listPendingServerRequestsByConversation = query(codex.queries.listPendingServerRequestsByConversation);
export const listThreadReasoningByConversation = query(codex.queries.listThreadReasoningByConversation);
