export {
  defineDispatchManagedHostEndpoints,
  defineRuntimeOwnedHostEndpoints,
  defineDispatchManagedHostSlice,
  defineRuntimeOwnedHostSlice,
  type CodexHostSliceFeatures,
  type CodexHostSliceIngestMode,
  type CodexHostSliceProfile,
  type CodexHostSliceThreadMode,
  type DefineDispatchManagedHostEndpointsOptions,
  type DefineRuntimeOwnedHostEndpointsOptions,
  type DefineDispatchManagedHostSliceOptions,
  type DefineRuntimeOwnedHostSliceOptions,
  type DispatchManagedHostDefinitions,
  type RuntimeOwnedHostDefinitions,
} from "./convexPreset.js";
export { wrapHostDefinitions } from "./wrapDefinitions.js";
export {
  HOST_PRESET_DEFINITIONS,
  HOST_SURFACE_MANIFEST,
  type HostSurfaceProfile,
  type HostSurfaceMutationKey,
  type HostSurfaceQueryKey,
} from "./surfaceManifest.js";

export {
  ingestBatchSafe,
  listThreadMessagesForHooks,
  listThreadReasoningForHooks,
  type HostInboundLifecycleEvent,
  type HostInboundStreamDelta,
  type HostMessagesForHooksArgs,
  type HostReasoningForHooksArgs,
  type HostStreamArgs,
  type HostSyncRuntimeOptions,
} from "./convex.js";

export {
  normalizeInboundDeltas,
  type NormalizedInboundDelta,
  type NormalizedInboundLifecycleEvent,
  type NormalizedInboundStreamDelta,
} from "./normalizeInboundDeltas.js";

export {
  RECOVERABLE_INGEST_ERROR_CODES,
  isRecoverableIngestError,
  isSessionForbidden,
  isThreadForbidden,
  isThreadMissing,
  parseErrorCode,
} from "../errors.js";

export {
  computeDataHygiene,
  computeDurableHistoryStats,
  computePersistenceStats,
  enqueueTurnDispatchForActor,
  claimNextTurnDispatchForActor,
  markTurnDispatchStartedForActor,
  markTurnDispatchCompletedForActor,
  markTurnDispatchFailedForActor,
  cancelTurnDispatchForActor,
  getTurnDispatchStateForActor,
  dispatchObservabilityForActor,
  dataHygiene,
  durableHistoryStats,
  ensureSession,
  ensureThreadByCreate,
  ensureThreadByResolve,
  ingestBatchMixed,
  ingestBatchStreamOnly,
  ingestEventMixed,
  ingestEventStreamOnly,
  interruptTurnForHooksForActor,
  isStreamStatSummary,
  listPendingApprovalsForHooksForActor,
  listPendingServerRequestsForHooksForActor,
  listThreadMessagesForHooksForActor,
  listThreadReasoningForHooksForActor,
  listTurnMessagesForHooksForActor,
  persistenceStats,
  respondApprovalForHooksForActor,
  resolvePendingServerRequestForHooksForActor,
  threadSnapshot,
  threadSnapshotSafe,
  upsertPendingServerRequestForHooksForActor,
  vHostActorContext,
  vHostDataHygiene,
  vHostDurableHistoryStats,
  vHostDispatchStatus,
  vHostDispatchObservability,
  vHostEnqueueTurnDispatchResult,
  vHostClaimedTurnDispatch,
  vHostTurnDispatchState,
  vHostTurnInput,
  vHostEnsureSessionResult,
  vHostIngestSafeResult,
  vHostLifecycleInboundEvent,
  vHostPersistenceStats,
  vHostStreamArgs,
  vHostStreamInboundEvent,
  vHostSyncRuntimeOptions,
  type CodexHostComponentRefs,
  type CodexHostComponentsInput,
  type HostActorContext,
} from "./convexSlice.js";
