import {
  HOST_PRESET_DEFINITIONS,
  HOST_SURFACE_MANIFEST,
  type HostSurfaceProfile,
} from "./surfaceManifest.js";

const PRESET_BY_PROFILE = {
  dispatchManaged: "defineDispatchManagedHostSlice",
  runtimeOwned: "defineRuntimeOwnedHostSlice",
} as const;

export type HostChatGeneratedTemplateOptions = {
  profile: HostSurfaceProfile;
  serverDeviceIdDefault: string;
};

export type HostWiringSmokeScriptOptions = {
  resolverImportPath: string;
  actorDeviceIdDefault: string;
  includeConvexDirEnv: boolean;
  label: string;
  prioritizeVite: boolean;
};

function quotedList(items: readonly string[]): string {
  return items.map((item) => `\`${item}\``).join(", ");
}

function renderExportLines(kind: "mutations" | "queries", keys: readonly string[]): string {
  const builder = kind === "mutations" ? "mutation" : "query";
  const source = kind === "mutations" ? "mutations" : "queries";
  return keys
    .map((key) => `export const ${key} = ${builder}(defs.${source}.${key});`)
    .join("\n");
}

function intersectOrdered(first: readonly string[], second: readonly string[]): string[] {
  const secondSet = new Set(second);
  return first.filter((item) => secondSet.has(item));
}

function differenceOrdered(first: readonly string[], second: readonly string[]): string[] {
  const secondSet = new Set(second);
  return first.filter((item) => !secondSet.has(item));
}

function renderBulletList(items: readonly string[]): string {
  return items.map((item) => `- \`${item}\``).join("\n");
}

export function renderHostChatGenerated(options: HostChatGeneratedTemplateOptions): string {
  const presetBuilder = PRESET_BY_PROFILE[options.profile];
  const surface = HOST_SURFACE_MANIFEST[options.profile];

  return `/**\n * AUTO-GENERATED FILE.\n *\n * Generated by:\n *   node ./packages/codex-local-component/scripts/generate-host-surfaces.mjs\n *\n * Do not edit this file directly. Add host-specific APIs in \`chat.extensions.ts\`.\n */\nimport { query, mutation } from "./_generated/server";\nimport { components } from "./_generated/api";\nimport {\n  ${presetBuilder},\n  type HostActorContext,\n} from "@zakstam/codex-local-component/host/convex";\n\nexport const SERVER_ACTOR: HostActorContext = Object.freeze({\n  tenantId: process.env.ACTOR_TENANT_ID ?? "demo-tenant",\n  userId: process.env.ACTOR_USER_ID ?? "demo-user",\n  deviceId: process.env.ACTOR_DEVICE_ID ?? "${options.serverDeviceIdDefault}",\n});\n\nconst defs = ${presetBuilder}({\n  components,\n  serverActor: SERVER_ACTOR,\n});\n\n${renderExportLines("mutations", surface.mutations)}\n\n${renderExportLines("queries", surface.queries)}\n`;
}

export function renderHostChatEntryModule(): string {
  return `/**\n * AUTO-GENERATED FILE.\n *\n * Generated by:\n *   node ./packages/codex-local-component/scripts/generate-host-surfaces.mjs\n */\nexport * from "./chat.generated";\nexport * from "./chat.extensions";\n`;
}

export function renderHostExtensionsScaffold(): string {
  return `/**\n * Host-specific Convex endpoints live here.\n *\n * Keep generated host wrapper exports in \`chat.generated.ts\`.\n */\nexport {};\n`;
}

export function renderHostPresetMatrixMarkdown(): string {
  const dispatch = HOST_SURFACE_MANIFEST.dispatchManaged;
  const runtime = HOST_SURFACE_MANIFEST.runtimeOwned;

  const commonQueries = intersectOrdered(dispatch.queries, runtime.queries);
  const dispatchOnlyQueries = differenceOrdered(dispatch.queries, commonQueries);
  const runtimeOnlyQueries = differenceOrdered(runtime.queries, commonQueries);

  const commonMutations = intersectOrdered(dispatch.mutations, runtime.mutations);
  const dispatchOnlyMutations = differenceOrdered(dispatch.mutations, commonMutations);

  const tableHeader = [
    "| Preset builder | Profile | Ingest mode | Thread mode | Intended host |",
    "| --- | --- | --- | --- | --- |",
  ].join("\n");

  const tableRows = HOST_PRESET_DEFINITIONS.map((preset) =>
    `| \`${preset.builder}\` | \`${preset.profile}\` | \`${preset.ingestMode}\` | \`${preset.threadMode}\` | ${preset.intendedHost} |`,
  ).join("\n");

  return `<!-- AUTO-GENERATED by packages/codex-local-component/scripts/generate-host-surfaces.mjs -->\n\n# Host Preset Matrix\n\nCanonical source for host preset surfaces.\n\n## Presets\n\n${tableHeader}\n${tableRows}\n\n## Deterministic query surface\n\nAll focused preset builders include:\n\n${renderBulletList(commonQueries)}\n\nAdditional query endpoints:\n\n- Dispatch-managed only: ${quotedList(dispatchOnlyQueries)}\n- Runtime-owned only: ${quotedList(runtimeOnlyQueries)}\n\n## Deterministic mutation surface\n\nAll focused preset builders include:\n\n${renderBulletList(commonMutations)}\n\nDispatch-managed additionally includes:\n\n${renderBulletList(dispatchOnlyMutations)}\n\n## Wiring preflight\n\nCall \`validateHostWiring\` after deploy/startup to fail fast on component mount drift.\n\nExample:\n\n\`\`\`ts\nawait ctx.runQuery(api.chat.validateHostWiring, {\n  actor,\n});\n\`\`\`\n\nResponse shape:\n\n- \`ok: boolean\`\n- \`checks: Array<{ name: string; ok: boolean; error?: string }>\`\n\nIf \`ok\` is false, one or more required \`components.codexLocal.*\` paths are not reachable in the current deployment.\n`;
}

export function renderHostWiringSmokeScript(options: HostWiringSmokeScriptOptions): string {
  return `import assert from "node:assert/strict";\nimport { ConvexHttpClient } from "convex/browser";\nimport { api } from "../convex/_generated/api.js";\nimport { resolveConvexUrl } from "${options.resolverImportPath}";\n\nasync function main() {\n  const convexUrl = resolveConvexUrl({\n    includeConvexDirEnv: ${options.includeConvexDirEnv ? "true" : "false"},\n    prioritizeVite: ${options.prioritizeVite ? "true" : "false"},\n  });\n  assert.ok(convexUrl, "Missing Convex URL. Run \`pnpm run dev:convex:once\` first.");\n\n  const convex = new ConvexHttpClient(convexUrl);\n  const actor = {\n    tenantId: process.env.ACTOR_TENANT_ID ?? "demo-tenant",\n    userId: process.env.ACTOR_USER_ID ?? "demo-user",\n    deviceId: process.env.ACTOR_DEVICE_ID ?? "${options.actorDeviceIdDefault}",\n  };\n  const validation = await convex.query(api.chat.validateHostWiring, { actor });\n  assert.equal(validation.ok, true, \`validateHostWiring failed: \${JSON.stringify(validation.checks)}\`);\n  console.log("${options.label} wiring smoke passed");\n}\n\nmain().catch((error) => {\n  const reason = error instanceof Error ? error.message : String(error);\n  console.error("${options.label} wiring smoke failed: " + reason);\n  process.exit(1);\n});\n`;
}
